import 'package:flutter/material.dart';
import 'package:flutter_colorpicker/flutter_colorpicker.dart';
import 'package:wurp/logic/themes/theme_model.dart';

class ThemeEditorScreen extends StatefulWidget {
  final CustomThemeModel? existingTheme;

  const ThemeEditorScreen({super.key, this.existingTheme});

  @override
  State<ThemeEditorScreen> createState() => _ThemeEditorScreenState();
}

class _ThemeEditorScreenState extends State<ThemeEditorScreen> {
  late final TextEditingController _nameController;
  late CustomThemeColors _colors;

  @override
  void initState() {
    super.initState();
    final t = widget.existingTheme;
    _nameController = TextEditingController(text: t?.name ?? '');
    _colors = t?.colors ?? CustomThemeColors.fromPrimary(const Color(0xFF6C5443));
  }

  @override
  void dispose() {
    _nameController.dispose();
    super.dispose();
  }


  Future<void> _pickColor({
    required String label,
    required Color current,
    required ValueChanged<Color> onPicked,
  }) async {
    Color temp = current;
    final result = await showDialog<Color>(
      context: context,
      builder: (ctx) => AlertDialog(
        title: Text('choose $label'),
        contentPadding: const EdgeInsets.fromLTRB(16, 16, 16, 0),
        content: SizedBox(
          width: 320,
          child: SingleChildScrollView(
            child: ColorPicker(
              pickerColor: current,
              onColorChanged: (c) => temp = c,
              enableAlpha: false,
              labelTypes: const [ColorLabelType.hex, ColorLabelType.rgb],
              pickerAreaHeightPercent: 0.7,
            ),
          ),
        ),
        actions: [
          TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('Cancel')),
          FilledButton(
            onPressed: () => Navigator.pop(ctx, temp),
            child: const Text('Apply'),
          ),
        ],
      ),
    );
    if (result != null) setState(() => onPicked(result));
  }
  
  Future<void> _showAutoGenerateDialog() async {
    Color seedPrimary   = _colors.primary;
    Color? seedSecondary;
    Color? seedTertiary;
    bool useDark        = _colors.isDark;
    bool useSecondary   = false;
    bool useTertiary    = false;

    await showDialog<void>(
      context: context,
      builder: (ctx) => StatefulBuilder(
        builder: (ctx, setLocal) {
          return AlertDialog(
            title: const Text('Auto-Generate Theme'),
            content: SingleChildScrollView(
              child: Column(
                mainAxisSize: MainAxisSize.min,
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  const Text(
                    'Choose 1-3 seed colors to generate a matching palette. Secondary and tertiary seeds are optional; if left empty, they will be automatically derived from the primary seed.',
                    style: TextStyle(fontSize: 13, color: Colors.grey),
                  ),
                  const SizedBox(height: 16),

                  _SeedRow(
                    label: 'Primary (Required)',
                    color: seedPrimary,
                    enabled: true,
                    onToggle: null,
                    onColorTap: () async {
                      Color temp = seedPrimary;
                      await showDialog<void>(
                        context: ctx,
                        builder: (c2) => AlertDialog(
                          title: const Text('Primary Seed'),
                          content: SizedBox(
                            width: 300,
                            child: SingleChildScrollView(
                              child: ColorPicker(
                                pickerColor: seedPrimary,
                                onColorChanged: (c) => temp = c,
                                enableAlpha: false,
                                labelTypes: const [ColorLabelType.hex],
                              ),
                            ),
                          ),
                          actions: [
                            FilledButton(
                              onPressed: () => Navigator.pop(c2),
                              child: const Text('OK'),
                            ),
                          ],
                        ),
                      );
                      setLocal(() => seedPrimary = temp);
                    },
                  ),
                  const SizedBox(height: 12),

                  _SeedRow(
                    label: 'Secondary (optional)',
                    color: seedSecondary ?? HSLColor.fromColor(seedPrimary).withHue((HSLColor.fromColor(seedPrimary).hue + 30) % 360).toColor(),
                    enabled: useSecondary,
                    onToggle: (v) => setLocal(() {
                      useSecondary  = v;
                      seedSecondary = v ? seedSecondary ?? _colors.secondary : null;
                    }),
                    onColorTap: !useSecondary ? null : () async {
                      Color temp = seedSecondary ?? _colors.secondary;
                      await showDialog<void>(
                        context: ctx,
                        builder: (c2) => AlertDialog(
                          title: const Text('Secondary Seed'),
                          content: SizedBox(
                            width: 300,
                            child: SingleChildScrollView(
                              child: ColorPicker(
                                pickerColor: temp,
                                onColorChanged: (c) => temp = c,
                                enableAlpha: false,
                                labelTypes: const [ColorLabelType.hex],
                              ),
                            ),
                          ),
                          actions: [
                            FilledButton(
                              onPressed: () => Navigator.pop(c2),
                              child: const Text('OK'),
                            ),
                          ],
                        ),
                      );
                      setLocal(() => seedSecondary = temp);
                    },
                  ),
                  const SizedBox(height: 12),

                  _SeedRow(
                    label: 'Tertiary (optional)',
                    color: seedTertiary ?? HSLColor.fromColor(seedPrimary).withHue((HSLColor.fromColor(seedPrimary).hue + 60) % 360).toColor(),
                    enabled: useTertiary,
                    onToggle: (v) => setLocal(() {
                      useTertiary  = v;
                      seedTertiary = v ? seedTertiary ?? _colors.tertiary : null;
                    }),
                    onColorTap: !useTertiary ? null : () async {
                      Color temp = seedTertiary ?? _colors.tertiary;
                      await showDialog<void>(
                        context: ctx,
                        builder: (c2) => AlertDialog(
                          title: const Text('Tertiary Seed'),
                          content: SizedBox(
                            width: 300,
                            child: SingleChildScrollView(
                              child: ColorPicker(
                                pickerColor: temp,
                                onColorChanged: (c) => temp = c,
                                enableAlpha: false,
                                labelTypes: const [ColorLabelType.hex],
                              ),
                            ),
                          ),
                          actions: [
                            FilledButton(
                              onPressed: () => Navigator.pop(c2),
                              child: const Text('OK'),
                            ),
                          ],
                        ),
                      );
                      setLocal(() => seedTertiary = temp);
                    },
                  ),
                  const SizedBox(height: 20),
                  const Divider(),
                  const SizedBox(height: 8),

                  Row(
                    children: [
                      const Icon(Icons.dark_mode_outlined, size: 20),
                      const SizedBox(width: 10),
                      const Expanded(child: Text('Dark Mode')),
                      Switch(
                        value: useDark,
                        onChanged: (v) => setLocal(() => useDark = v),
                      ),
                    ],
                  ),
                ],
              ),
            ),
            actions: [
              TextButton(
                onPressed: () => Navigator.pop(ctx),
                child: const Text('Cancel'),
              ),
              FilledButton.icon(
                icon: const Icon(Icons.auto_fix_high, size: 16),
                label: const Text('Generate'),
                onPressed: () {
                  setState(() {
                    _colors = CustomThemeColors.fromSeeds(
                      primary:   seedPrimary,
                      secondary: useSecondary ? seedSecondary : null,
                      tertiary:  useTertiary  ? seedTertiary  : null,
                      dark:      useDark,
                    );
                  });
                  Navigator.pop(ctx);
                },
              ),
            ],
          );
        },
      ),
    );
  }
  
  void _save() {
    final name = _nameController.text.trim();
    Navigator.pop(
      context,
      CustomThemeModel(
        id:        widget.existingTheme?.id ?? UniqueKey().toString(),
        name:      name.isEmpty ? 'Custom Theme' : name,
        colors:    _colors,
        createdBy: widget.existingTheme?.createdBy,
        likesCount: widget.existingTheme?.likesCount ?? 0,
        isPublic:  widget.existingTheme?.isPublic ?? false,
        createdAt: widget.existingTheme?.createdAt,
      ),
    );
  }
  
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text(widget.existingTheme == null ? 'Create theme' : 'Edit theme'),
        actions: [
          Tooltip(
            message: _colors.isDark ? 'Switch to Light mode' : 'Switch to Dark mode',
            child: IconButton(
              icon: Icon(_colors.isDark ? Icons.light_mode_outlined : Icons.dark_mode_outlined),
              onPressed: () => setState(() {
                _colors = CustomThemeColors.fromSeeds(
                  primary:   _colors.primary,
                  secondary: _colors.secondary,
                  tertiary:  _colors.tertiary,
                  dark:      !_colors.isDark,
                );
              }),
            ),
          ),
          TextButton.icon(
            onPressed: _showAutoGenerateDialog,
            icon: const Icon(Icons.auto_fix_high, size: 16),
            label: const Text('Auto'),
          ),
          const SizedBox(width: 4),
        ],
      ),
      body: Column(
        children: [
          _ThemePreview(
            colors: _colors,
            name:   _nameController.text.isEmpty ? 'Mein Theme' : _nameController.text,
          ),

          Expanded(
            child: ListView(
              padding: const EdgeInsets.fromLTRB(16, 8, 16, 100),
              children: [
                TextField(
                  controller: _nameController,
                  decoration: const InputDecoration(
                    labelText: 'Theme-Name',
                    border: OutlineInputBorder(),
                    prefixIcon: Icon(Icons.label_outline),
                  ),
                  onChanged: (_) => setState(() {}),
                ),
                const SizedBox(height: 4),

                AnimatedSwitcher(
                  duration: const Duration(milliseconds: 200),
                  child: _colors.isDark
                      ? Padding(
                    key: const ValueKey('dark'),
                    padding: const EdgeInsets.only(top: 8),
                    child: Chip(
                      avatar: const Icon(Icons.dark_mode, size: 16),
                      label: const Text('Dark Theme'),
                      backgroundColor: Colors.grey[850],
                      labelStyle: const TextStyle(color: Colors.white70),
                    ),
                  )
                      : const SizedBox.shrink(key: ValueKey('light')),
                ),

                const _SectionHeader('Brand-Colors'),
                _colorRow('Primary',     _colors.primary,     (c) => _colors = _colors.copyWith(primary: c)),
                _colorRow('On Primary',  _colors.onPrimary,   (c) => _colors = _colors.copyWith(onPrimary: c)),
                _colorRow('Secondary',   _colors.secondary,   (c) => _colors = _colors.copyWith(secondary: c)),
                _colorRow('On Secondary',_colors.onSecondary, (c) => _colors = _colors.copyWith(onSecondary: c)),
                _colorRow('Tertiary',    _colors.tertiary,    (c) => _colors = _colors.copyWith(tertiary: c)),
                _colorRow('On Tertiary', _colors.onTertiary,  (c) => _colors = _colors.copyWith(onTertiary: c)),

                const _SectionHeader('Surface-Colors'),
                _colorRow('Background',    _colors.background,   (c) => _colors = _colors.copyWith(background: c)),
                _colorRow('On Background', _colors.onBackground, (c) => _colors = _colors.copyWith(onBackground: c)),
                _colorRow('Surface',       _colors.surface,      (c) => _colors = _colors.copyWith(surface: c)),
                _colorRow('On Surface',    _colors.onSurface,    (c) => _colors = _colors.copyWith(onSurface: c)),

                const _SectionHeader('Status-Colors'),
                _colorRow('Error',    _colors.error,   (c) => _colors = _colors.copyWith(error: c)),
                _colorRow('On Error', _colors.onError, (c) => _colors = _colors.copyWith(onError: c)),
              ],
            ),
          ),
        ],
      ),
      floatingActionButton: FloatingActionButton.extended(
        onPressed: _save,
        icon: const Icon(Icons.save_rounded),
        label: const Text('Speichern'),
      ),
    );
  }

  Widget _colorRow(String label, Color color, void Function(Color) update) {
    return _ColorRow(
      label: label,
      color: color,
      onTap: () => _pickColor(
        label: label,
        current: color,
        onPicked: (c) => setState(() => update(c)),
      ),
    );
  }
}

// ──────────────────────────────────────────────────────────────────────────────
// Seed-row widget used inside the auto-generate dialog
// ──────────────────────────────────────────────────────────────────────────────

class _SeedRow extends StatelessWidget {
  final String label;
  final Color color;
  final bool enabled;
  final ValueChanged<bool>? onToggle;
  final VoidCallback? onColorTap;

  const _SeedRow({
    required this.label,
    required this.color,
    required this.enabled,
    required this.onToggle,
    required this.onColorTap,
  });

  @override
  Widget build(BuildContext context) {
    return Row(
      children: [
        // Swatch
        GestureDetector(
          onTap: onColorTap,
          child: AnimatedContainer(
            duration: const Duration(milliseconds: 200),
            width: 40,
            height: 40,
            decoration: BoxDecoration(
              color: enabled ? color : color.withValues(alpha: 0.3),
              borderRadius: BorderRadius.circular(10),
              border: Border.all(color: Colors.black12),
            ),
            child: enabled
                ? const Icon(Icons.colorize, size: 16, color: Colors.white70)
                : null,
          ),
        ),
        const SizedBox(width: 12),
        Expanded(
          child: Text(
            label,
            style: TextStyle(
              color: enabled ? null : Colors.grey,
              fontWeight: enabled ? FontWeight.w500 : FontWeight.normal,
            ),
          ),
        ),
        if (onToggle != null)
          Switch(value: enabled, onChanged: onToggle),
      ],
    );
  }
}

// Shared small widgets
class _SectionHeader extends StatelessWidget {
  final String title;
  const _SectionHeader(this.title);

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.fromLTRB(0, 20, 0, 6),
      child: Text(
        title.toUpperCase(),
        style: Theme.of(context).textTheme.labelSmall?.copyWith(
          color: Theme.of(context).colorScheme.primary,
          letterSpacing: 1.4,
          fontWeight: FontWeight.w700,
        ),
      ),
    );
  }
}

class _ColorRow extends StatelessWidget {
  final String label;
  final Color color;
  final VoidCallback onTap;

  const _ColorRow({required this.label, required this.color, required this.onTap});

  @override
  Widget build(BuildContext context) {
    final hex     = '#${color.toARGB32().toRadixString(16).padLeft(8, '0').substring(2).toUpperCase()}';
    final isLight = color.computeLuminance() > 0.45;

    return InkWell(
      onTap: onTap,
      borderRadius: BorderRadius.circular(12),
      child: Padding(
        padding: const EdgeInsets.symmetric(vertical: 6),
        child: Row(
          children: [
            // Swatch
            Container(
              width: 52,
              height: 52,
              decoration: BoxDecoration(
                color: color,
                borderRadius: BorderRadius.circular(12),
                border: Border.all(color: Colors.black.withValues(alpha: 0.08)),
                boxShadow: [BoxShadow(color: color.withValues(alpha: 0.35), blurRadius: 6, offset: const Offset(0, 2))],
              ),
              child: Icon(Icons.colorize_rounded, size: 18, color: isLight ? Colors.black45 : Colors.white54),
            ),
            const SizedBox(width: 14),
            Expanded(
              child: Text(label, style: const TextStyle(fontWeight: FontWeight.w600, fontSize: 14)),
            ),
            // Hex badge
            Container(
              padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
              decoration: BoxDecoration(color: Colors.grey[100], borderRadius: BorderRadius.circular(6)),
              child: Text(hex, style: const TextStyle(fontFamily: 'monospace', fontSize: 11)),
            ),
            const SizedBox(width: 4),
            const Icon(Icons.chevron_right, color: Colors.grey, size: 18),
          ],
        ),
      ),
    );
  }
}

class _ThemePreview extends StatelessWidget {
  final CustomThemeColors colors;
  final String name;

  const _ThemePreview({required this.colors, required this.name});

  @override
  Widget build(BuildContext context) {
    return Container(
      height: 260,
      width: double.infinity,
      color: Colors.grey[300],
      child: Column(
        children: [
          Padding(
            padding: const EdgeInsets.symmetric(vertical: 6),
            child: Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                Text(
                  'Preview',
                  style: Theme.of(context)
                      .textTheme
                      .labelSmall
                      ?.copyWith(color: Colors.grey[700], letterSpacing: 1.2),
                ),
                const SizedBox(width: 8),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 6, vertical: 2),
                  decoration: BoxDecoration(
                    color: colors.isDark ? Colors.grey[800] : Colors.white,
                    borderRadius: BorderRadius.circular(6),
                  ),
                  child: Row(
                    mainAxisSize: MainAxisSize.min,
                    children: [
                      Icon(
                        colors.isDark ? Icons.dark_mode : Icons.light_mode,
                        size: 11,
                        color: colors.isDark ? Colors.white70 : Colors.orange[700],
                      ),
                      const SizedBox(width: 3),
                      Text(
                        colors.isDark ? 'Dark' : 'Light',
                        style: TextStyle(
                          fontSize: 10,
                          color: colors.isDark ? Colors.white70 : Colors.grey[700],
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                    ],
                  ),
                ),
              ],
            ),
          ),
          Expanded(
            child: Center(
              child: AspectRatio(
                aspectRatio: 9 / 16,
                child: ClipRRect(
                  borderRadius: BorderRadius.circular(16),
                  child: _MockApp(colors: colors, name: name),
                ),
              ),
            ),
          ),
          const SizedBox(height: 8),
        ],
      ),
    );
  }
}

class _MockApp extends StatelessWidget {
  final CustomThemeColors c;
  final String name;

  const _MockApp({required CustomThemeColors colors, required this.name}) : c = colors;

  @override
  Widget build(BuildContext context) {
    return Container(
      color: c.background,
      child: Column(
        children: [
          Container(
            color: c.primary,
            padding: const EdgeInsets.symmetric(horizontal: 10, vertical: 8),
            child: Row(
              children: [
                Icon(Icons.arrow_back, color: c.onPrimary, size: 14),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(name,
                      style: TextStyle(color: c.onPrimary, fontWeight: FontWeight.bold, fontSize: 12),
                      overflow: TextOverflow.ellipsis),
                ),
                Icon(Icons.search,    color: c.onPrimary, size: 14),
                const SizedBox(width: 6),
                Icon(Icons.more_vert, color: c.onPrimary, size: 14),
              ],
            ),
          ),

          Expanded(
            child: SingleChildScrollView(
              physics: const NeverScrollableScrollPhysics(),
              padding: const EdgeInsets.all(8),
              child: Column(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  _card(
                    color: c.surface,
                    shadow: true,
                    child: Column(
                      crossAxisAlignment: CrossAxisAlignment.start,
                      children: [
                        Text('Card Title',
                            style: TextStyle(color: c.onSurface, fontWeight: FontWeight.bold, fontSize: 9)),
                        const SizedBox(height: 3),
                        Text('Description on the card.',
                            style: TextStyle(color: c.onSurface.withValues(alpha: 0.65), fontSize: 8)),
                        const SizedBox(height: 8),
                        Row(
                          mainAxisAlignment: MainAxisAlignment.end,
                          children: [
                            _outlinedBtn('Cancel', c.primary),
                            const SizedBox(width: 5),
                            _filledBtn('OK', c.primary, c.onPrimary),
                          ],
                        ),
                      ],
                    ),
                  ),
                  const SizedBox(height: 6),
                  Wrap(
                    spacing: 4,
                    children: ['Design', 'Colors', 'Theme'].map((l) => Container(
                      padding: const EdgeInsets.symmetric(horizontal: 7, vertical: 3),
                      decoration: BoxDecoration(
                        color: c.secondary.withValues(alpha: 0.18),
                        borderRadius: BorderRadius.circular(20),
                        border: Border.all(color: c.secondary.withValues(alpha: 0.45)),
                      ),
                      child: Text(l, style: TextStyle(color: c.secondary, fontSize: 7, fontWeight: FontWeight.w600)),
                    )).toList(),
                  ),
                  const SizedBox(height: 6),
                  _card(
                    color: c.tertiary.withValues(alpha: 0.15),
                    border: Border.all(color: c.tertiary.withValues(alpha: 0.4)),
                    child: Row(children: [
                      Icon(Icons.info_outline, color: c.tertiary, size: 11),
                      const SizedBox(width: 5),
                      Expanded(child: Text('Tertiary-Accent', style: TextStyle(color: c.tertiary, fontSize: 8))),
                    ]),
                  ),
                  const SizedBox(height: 6),
                  _card(
                    color: c.error.withValues(alpha: 0.10),
                    border: Border.all(color: c.error.withValues(alpha: 0.35)),
                    child: Row(children: [
                      Icon(Icons.error_outline, color: c.error, size: 11),
                      const SizedBox(width: 5),
                      Expanded(child: Text('Error status', style: TextStyle(color: c.error, fontSize: 8))),
                    ]),
                  ),
                ],
              ),
            ),
          ),

          Container(
            color: c.surface,
            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 6),
            child: Row(
              children: [
                _navIcon(Icons.home_rounded,         active: true,  c: c),
                _navIcon(Icons.explore_outlined,     active: false, c: c),
                _navIcon(Icons.notifications_outlined,active: false,c: c),
                _navIcon(Icons.person_outline,       active: false, c: c),
                const Spacer(),
                Container(
                  padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 5),
                  decoration: BoxDecoration(
                    color: c.primary,
                    borderRadius: BorderRadius.circular(12),
                    boxShadow: [BoxShadow(color: c.primary.withValues(alpha: 0.35), blurRadius: 6)],
                  ),
                  child: Row(mainAxisSize: MainAxisSize.min, children: [
                    Icon(Icons.add, color: c.onPrimary, size: 10),
                    const SizedBox(width: 3),
                    Text('Neu', style: TextStyle(color: c.onPrimary, fontSize: 8, fontWeight: FontWeight.bold)),
                  ]),
                ),
              ],
            ),
          ),
        ],
      ),
    );
  }

  Widget _card({required Color color, required Widget child, bool shadow = false, Border? border}) =>
      Container(
        width: double.infinity,
        padding: const EdgeInsets.all(8),
        decoration: BoxDecoration(
          color: color,
          borderRadius: BorderRadius.circular(8),
          border: border,
          boxShadow: shadow
              ? [BoxShadow(color: Colors.black.withValues(alpha: 0.08), blurRadius: 4, offset: const Offset(0, 2))]
              : null,
        ),
        child: child,
      );

  Widget _filledBtn(String l, Color bg, Color fg) => Container(
    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
    decoration: BoxDecoration(color: bg, borderRadius: BorderRadius.circular(20)),
    child: Text(l, style: TextStyle(color: fg, fontSize: 8, fontWeight: FontWeight.bold)),
  );

  Widget _outlinedBtn(String l, Color color) => Container(
    padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
    decoration: BoxDecoration(border: Border.all(color: color), borderRadius: BorderRadius.circular(20)),
    child: Text(l, style: TextStyle(color: color, fontSize: 8)),
  );

  Widget _navIcon(IconData icon, {required bool active, required CustomThemeColors c}) => Padding(
    padding: const EdgeInsets.symmetric(horizontal: 5),
    child: Icon(icon, size: 13, color: active ? c.primary : c.onSurface.withValues(alpha: 0.4)),
  );
}