// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDw6pLDntTwI-K_xpt3GuEx2pFIm6nP1l0',
    appId: '1:418845388234:web:103c81b1b635273460b333',
    messagingSenderId: '418845388234',
    projectId: 'scroller-wurp',
    authDomain: 'scroller-wurp.firebaseapp.com',
    storageBucket: 'scroller-wurp.firebasestorage.app',
    measurementId: 'G-GBK9WG921H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBzAXDJUkGDZebgmqC4T4K7lSKUQ8omw-w',
    appId: '1:418845388234:android:7596e04b7e5a068760b333',
    messagingSenderId: '418845388234',
    projectId: 'scroller-wurp',
    storageBucket: 'scroller-wurp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATXjCi14qbYOm3QoQRhs9p0rOQutXVTrE',
    appId: '1:418845388234:ios:2623c273d36caaef60b333',
    messagingSenderId: '418845388234',
    projectId: 'scroller-wurp',
    storageBucket: 'scroller-wurp.firebasestorage.app',
    iosBundleId: 'de.riddleNeon.wurp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATXjCi14qbYOm3QoQRhs9p0rOQutXVTrE',
    appId: '1:418845388234:ios:2623c273d36caaef60b333',
    messagingSenderId: '418845388234',
    projectId: 'scroller-wurp',
    storageBucket: 'scroller-wurp.firebasestorage.app',
    iosBundleId: 'de.riddleNeon.wurp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDw6pLDntTwI-K_xpt3GuEx2pFIm6nP1l0',
    appId: '1:418845388234:web:2dd303c87880a02060b333',
    messagingSenderId: '418845388234',
    projectId: 'scroller-wurp',
    authDomain: 'scroller-wurp.firebaseapp.com',
    storageBucket: 'scroller-wurp.firebasestorage.app',
    measurementId: 'G-YM3FX3M3RZ',
  );
}
