-- Task/Quiz DSL backend (no external scripts)
-- Run in Supabase SQL editor or as migration.

begin;

-- -------------------------------------------------
-- 1) Schema extensions: versions + attempts
-- -------------------------------------------------

create extension if not exists citext;

alter table public.tasks
  add column if not exists visibility text not null default 'public'
    check (visibility in ('private', 'unlisted', 'public')),
  add column if not exists current_version_id bigint;

create table if not exists public.task_versions (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  version_no integer not null,
  status text not null default 'draft' check (status in ('draft', 'published', 'archived')),
  title text not null default 'No Title Provided',
  ui jsonb not null default '{}'::jsonb,
  logic jsonb not null default '{"rules":[],"pass":{"min_score":0}}'::jsonb,
  created_by uuid not null default auth.uid(),
  created_at timestamptz not null default now(),
  published_at timestamptz,
  unique (task_id, version_no),
  check (jsonb_typeof(ui) = 'object'),
  check (jsonb_typeof(logic) = 'object')
);

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'tasks_current_version_id_fkey'
  ) then
    alter table public.tasks
      add constraint tasks_current_version_id_fkey
      foreign key (current_version_id)
      references public.task_versions(id)
      on delete set null;
  end if;
end $$;

create table if not exists public.task_attempts (
  id bigint generated by default as identity primary key,
  task_id bigint not null references public.tasks(id) on delete cascade,
  version_id bigint not null references public.task_versions(id) on delete cascade,
  user_id uuid not null default auth.uid(),
  answer_data jsonb not null default '{}'::jsonb,
  evaluation jsonb not null default '{}'::jsonb,
  is_correct boolean not null default false,
  xp_delta double precision not null default 0,
  created_at timestamptz not null default now(),
  check (jsonb_typeof(answer_data) = 'object'),
  check (jsonb_typeof(evaluation) = 'object')
);

create index if not exists idx_tasks_created_by on public.tasks(created_by);
create index if not exists idx_tasks_visibility on public.tasks(visibility);
create index if not exists idx_task_versions_task_id on public.task_versions(task_id);
create index if not exists idx_task_versions_status on public.task_versions(status);
create index if not exists idx_task_versions_ui_gin on public.task_versions using gin (ui);
create index if not exists idx_task_versions_logic_gin on public.task_versions using gin (logic);
create index if not exists idx_task_attempts_user_id on public.task_attempts(user_id);
create index if not exists idx_task_attempts_task_id on public.task_attempts(task_id);
create index if not exists idx_task_attempts_created_at on public.task_attempts(created_at);

create unique index if not exists profile_levels_user_category_uq
  on public.profile_levels(user_id, category);

-- Optional compatibility: task_solutions.data => jsonb
DO $$
declare
  v_data_type text;
begin
  select data_type
    into v_data_type
  from information_schema.columns
  where table_schema = 'public'
    and table_name = 'task_solutions'
    and column_name = 'data';

  if v_data_type is not null and v_data_type <> 'jsonb' then
    execute 'alter table public.task_solutions alter column data type jsonb using data::jsonb';
  end if;
end $$;

-- -------------------------------------------------
-- 2) Helpers for DSL evaluation
-- -------------------------------------------------

create or replace function public.quiz_logic_is_valid(p_logic jsonb)
returns boolean
language sql
immutable
as $$
  select
    jsonb_typeof(p_logic) = 'object'
    and (
      not (p_logic ? 'rules')
      or jsonb_typeof(p_logic->'rules') = 'array'
    )
    and (
      not (p_logic ? 'pass')
      or jsonb_typeof(p_logic->'pass') = 'object'
    );
$$;

create or replace function public.quiz_ref_value(
  p_ref jsonb,
  p_answers jsonb,
  p_vars jsonb,
  p_ctx jsonb default '{}'::jsonb
) returns jsonb
language plpgsql
immutable
as $$
declare
  v_source text;
  v_path text;
  v_path_arr text[];
begin
  if p_ref is null then
    return 'null'::jsonb;
  end if;

  if jsonb_typeof(p_ref) <> 'object' then
    return p_ref;
  end if;

  if p_ref ? 'const' then
    return p_ref->'const';
  end if;

  v_source := coalesce(p_ref->>'source', 'answers');
  v_path := coalesce(p_ref->>'path', '');
  v_path_arr := case when v_path = '' then array[]::text[] else string_to_array(v_path, '.') end;

  case v_source
    when 'answers' then return coalesce(p_answers #> v_path_arr, 'null'::jsonb);
    when 'vars' then return coalesce(p_vars #> v_path_arr, 'null'::jsonb);
    when 'ctx' then return coalesce(p_ctx #> v_path_arr, 'null'::jsonb);
    else return 'null'::jsonb;
  end case;
end;
$$;

create or replace function public.quiz_to_numeric(p_val jsonb)
returns numeric
language plpgsql
immutable
as $$
declare
  v_text text;
begin
  if p_val is null or p_val = 'null'::jsonb then
    return null;
  end if;

  if jsonb_typeof(p_val) = 'number' then
    return (p_val::text)::numeric;
  end if;

  v_text := p_val #>> '{}';
  if v_text is null then
    return null;
  end if;

  if v_text ~ '^-?[0-9]+(\.[0-9]+)?$' then
    return v_text::numeric;
  end if;

  return null;
end;
$$;

create or replace function public.quiz_eval_condition(
  p_cond jsonb,
  p_answers jsonb,
  p_vars jsonb,
  p_ctx jsonb default '{}'::jsonb
) returns boolean
language plpgsql
stable
as $$
declare
  v_op text;
  v_left jsonb;
  v_right jsonb;
  v_num_left numeric;
  v_num_right numeric;
  v_arg jsonb;
  v_list jsonb;
begin
  v_op := lower(coalesce(p_cond->>'op', 'eq'));

  if v_op = 'true' then
    return true;
  elsif v_op = 'false' then
    return false;
  elsif v_op = 'not' then
    return not public.quiz_eval_condition(coalesce(p_cond->'arg', '{"op":"false"}'::jsonb), p_answers, p_vars, p_ctx);
  elsif v_op = 'and' then
    for v_arg in
      select value
      from jsonb_array_elements(case when jsonb_typeof(p_cond->'args') = 'array' then p_cond->'args' else '[]'::jsonb end)
    loop
      if not public.quiz_eval_condition(v_arg, p_answers, p_vars, p_ctx) then
        return false;
      end if;
    end loop;
    return true;
  elsif v_op = 'or' then
    for v_arg in
      select value
      from jsonb_array_elements(case when jsonb_typeof(p_cond->'args') = 'array' then p_cond->'args' else '[]'::jsonb end)
    loop
      if public.quiz_eval_condition(v_arg, p_answers, p_vars, p_ctx) then
        return true;
      end if;
    end loop;
    return false;
  end if;

  v_left := public.quiz_ref_value(p_cond->'left', p_answers, p_vars, p_ctx);
  v_right := public.quiz_ref_value(p_cond->'right', p_answers, p_vars, p_ctx);

  if v_op = 'eq' then
    return v_left = v_right;
  elsif v_op = 'neq' then
    return v_left <> v_right;
  elsif v_op in ('gt', 'gte', 'lt', 'lte') then
    v_num_left := public.quiz_to_numeric(v_left);
    v_num_right := public.quiz_to_numeric(v_right);

    if v_num_left is null or v_num_right is null then
      return false;
    end if;

    if v_op = 'gt' then return v_num_left > v_num_right; end if;
    if v_op = 'gte' then return v_num_left >= v_num_right; end if;
    if v_op = 'lt' then return v_num_left < v_num_right; end if;
    return v_num_left <= v_num_right;
  elsif v_op = 'in' then
    v_list := v_right;
    if jsonb_typeof(v_list) <> 'array' then
      return false;
    end if;
    return exists (
      select 1
      from jsonb_array_elements(v_list) e
      where e.value = v_left
    );
  elsif v_op = 'contains' then
    if jsonb_typeof(v_left) = 'array' then
      return exists (
        select 1
        from jsonb_array_elements(v_left) e
        where e.value = v_right
      );
    elsif jsonb_typeof(v_left) = 'string' then
      return position(coalesce(v_right #>> '{}', '') in coalesce(v_left #>> '{}', '')) > 0;
    else
      return false;
    end if;
  elsif v_op = 'regex' then
    return coalesce(v_left #>> '{}', '') ~ coalesce(v_right #>> '{}', '');
  elsif v_op = 'exists' then
    return v_left is not null and v_left <> 'null'::jsonb;
  end if;

  return false;
end;
$$;

create or replace function public.evaluate_task_submission(
  p_task_id bigint,
  p_version_id bigint,
  p_answer_data jsonb
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_logic jsonb;
  v_answers jsonb;
  v_vars jsonb;
  v_rules jsonb;
  v_rule jsonb;
  v_when jsonb;
  v_then jsonb;
  v_else jsonb;
  v_passed boolean;
  v_trace jsonb := '[]'::jsonb;
  v_score numeric := 0;
  v_max_score numeric := 0;
  v_hard_fail boolean := false;
  v_pass_threshold numeric;
  v_is_correct boolean;
  v_xp_factor numeric := 0;
begin
  select tv.logic
    into v_logic
  from public.task_versions tv
  where tv.id = p_version_id
    and tv.task_id = p_task_id;

  if not found then
    raise exception 'Version % fuer Task % nicht gefunden', p_version_id, p_task_id;
  end if;

  if not public.quiz_logic_is_valid(v_logic) then
    raise exception 'Invalid logic JSON for task version %', p_version_id;
  end if;

  v_answers := case
    when p_answer_data ? 'answers' then coalesce(p_answer_data->'answers', '{}'::jsonb)
    else coalesce(p_answer_data, '{}'::jsonb)
  end;

  v_vars := coalesce(p_answer_data->'vars', '{}'::jsonb);
  v_rules := coalesce(v_logic->'rules', '[]'::jsonb);

  for v_rule in
    select value
    from jsonb_array_elements(case when jsonb_typeof(v_rules) = 'array' then v_rules else '[]'::jsonb end)
  loop
    v_when := coalesce(v_rule->'when', '{"op":"true"}'::jsonb);
    v_then := coalesce(v_rule->'then', '{}'::jsonb);
    v_else := coalesce(v_rule->'else', '{}'::jsonb);

    v_passed := public.quiz_eval_condition(v_when, v_answers, v_vars, jsonb_build_object('now', now()::text));

    if v_passed then
      if v_then ? 'max_score' then v_max_score := v_max_score + coalesce((v_then->>'max_score')::numeric, 0); end if;
      if v_then ? 'add_score' then v_score := v_score + coalesce((v_then->>'add_score')::numeric, 0); end if;
      if v_then ? 'set_vars' and jsonb_typeof(v_then->'set_vars') = 'object' then
        v_vars := v_vars || (v_then->'set_vars');
      end if;
      if lower(coalesce(v_then->>'fail', 'false')) = 'true' then v_hard_fail := true; end if;
    else
      if v_else ? 'max_score' then v_max_score := v_max_score + coalesce((v_else->>'max_score')::numeric, 0); end if;
      if v_else ? 'add_score' then v_score := v_score + coalesce((v_else->>'add_score')::numeric, 0); end if;
      if v_else ? 'set_vars' and jsonb_typeof(v_else->'set_vars') = 'object' then
        v_vars := v_vars || (v_else->'set_vars');
      end if;
      if lower(coalesce(v_else->>'fail', 'false')) = 'true' then v_hard_fail := true; end if;
    end if;

    v_trace := v_trace || jsonb_build_array(jsonb_build_object(
      'rule_id', coalesce(v_rule->>'id', md5(v_rule::text)),
      'passed', v_passed
    ));
  end loop;

  v_pass_threshold := nullif(coalesce(v_logic#>>'{pass,min_score}', ''), '')::numeric;
  if v_pass_threshold is null then
    v_pass_threshold := v_max_score;
  end if;

  v_is_correct := (not v_hard_fail) and (v_score >= coalesce(v_pass_threshold, 0));

  if v_max_score > 0 then
    v_xp_factor := greatest(least(v_score / v_max_score, 1), 0);
  else
    v_xp_factor := case when v_is_correct then 1 else 0 end;
  end if;

  return jsonb_build_object(
    'is_correct', v_is_correct,
    'score', v_score,
    'max_score', v_max_score,
    'pass_threshold', coalesce(v_pass_threshold, 0),
    'xp_factor', v_xp_factor,
    'vars', v_vars,
    'trace', v_trace
  );
end;
$$;

-- -------------------------------------------------
-- 3) RPC for authoring workflow
-- -------------------------------------------------

create or replace function public.create_task_draft_version(
  p_task_id bigint,
  p_title text,
  p_ui jsonb default '{}'::jsonb,
  p_logic jsonb default '{"rules":[],"pass":{"min_score":0}}'::jsonb
) returns public.task_versions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_next integer;
  v_row public.task_versions;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  if not exists (
    select 1 from public.tasks t where t.id = p_task_id and t.created_by = v_uid
  ) then
    raise exception 'Only owner can create draft versions';
  end if;

  if not public.quiz_logic_is_valid(p_logic) then
    raise exception 'Invalid logic JSON';
  end if;

  if jsonb_typeof(p_ui) <> 'object' then
    raise exception 'UI JSON must be an object';
  end if;

  select coalesce(max(version_no), 0) + 1
  into v_next
  from public.task_versions
  where task_id = p_task_id;

  insert into public.task_versions(task_id, version_no, status, title, ui, logic, created_by)
  values (p_task_id, v_next, 'draft', coalesce(p_title, 'No Title Provided'), p_ui, p_logic, v_uid)
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.clone_task_version(
  p_task_id bigint,
  p_source_version_id bigint,
  p_new_title text default null
) returns public.task_versions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_source public.task_versions;
  v_next integer;
  v_row public.task_versions;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  if not exists (
    select 1 from public.tasks t where t.id = p_task_id and t.created_by = v_uid
  ) then
    raise exception 'Only owner can clone versions';
  end if;

  select *
    into v_source
  from public.task_versions
  where id = p_source_version_id
    and task_id = p_task_id;

  if not found then
    raise exception 'Source version not found';
  end if;

  select coalesce(max(version_no), 0) + 1
  into v_next
  from public.task_versions
  where task_id = p_task_id;

  insert into public.task_versions(task_id, version_no, status, title, ui, logic, created_by)
  values (
    p_task_id,
    v_next,
    'draft',
    coalesce(p_new_title, v_source.title || ' (copy)'),
    v_source.ui,
    v_source.logic,
    v_uid
  )
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function public.publish_task_version(
  p_task_id bigint,
  p_version_id bigint,
  p_make_current boolean default true
) returns public.task_versions
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_row public.task_versions;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  if not exists (
    select 1 from public.tasks t where t.id = p_task_id and t.created_by = v_uid
  ) then
    raise exception 'Only owner can publish versions';
  end if;

  update public.task_versions
  set status = 'published',
      published_at = now()
  where id = p_version_id
    and task_id = p_task_id
  returning * into v_row;

  if not found then
    raise exception 'Version not found';
  end if;

  if p_make_current then
    update public.tasks
    set current_version_id = p_version_id
    where id = p_task_id;
  end if;

  return v_row;
end;
$$;

-- -------------------------------------------------
-- 4) Solve RPC (DSL only)
-- -------------------------------------------------

create or replace function public.solve_task_v2(
  p_task_id bigint,
  p_answer_data jsonb,
  p_version_id bigint default null
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_uid uuid := auth.uid();
  v_task record;
  v_version_id bigint;
  v_eval jsonb;
  v_is_correct boolean;
  v_xp_factor numeric;
  v_delta double precision;
  v_valid_subjects text[] := array[]::text[];
  v_invalid_subjects text[] := array[]::text[];
  v_subject text;
begin
  if v_uid is null then
    raise exception 'Not authenticated';
  end if;

  select t.id, t.subjects, t.xp_reward, t.xp_punishment, t.current_version_id, t.created_by, t.visibility
  into v_task
  from public.tasks t
  where t.id = p_task_id;

  if not found then
    raise exception 'Task % not found', p_task_id;
  end if;

  v_version_id := coalesce(p_version_id, v_task.current_version_id);
  if v_version_id is null then
    raise exception 'Task % has no current version', p_task_id;
  end if;

  if not exists (
    select 1
    from public.task_versions tv
    where tv.id = v_version_id
      and tv.task_id = p_task_id
      and (tv.status = 'published' or v_task.created_by = v_uid)
  ) then
    raise exception 'Version is not accessible';
  end if;

  v_eval := public.evaluate_task_submission(
    p_task_id,
    v_version_id,
    coalesce(p_answer_data, '{}'::jsonb)
  );

  v_is_correct := coalesce((v_eval->>'is_correct')::boolean, false);
  v_xp_factor := coalesce((v_eval->>'xp_factor')::numeric, 0);

  if v_is_correct then
    v_delta := (v_task.xp_reward * greatest(least(v_xp_factor, 1), 0))::double precision;
  else
    v_delta := (-v_task.xp_punishment)::double precision;
  end if;

  -- Build valid/invalid subjects without assuming a specific categories column name.
  -- If the FK check fails on insert, the subject is treated as invalid and skipped.
  for v_subject in
    select s from unnest(v_task.subjects) as s
  loop
    begin
      insert into public.profile_levels(user_id, category, level)
      values (v_uid, v_subject, 0)
      on conflict (user_id, category) do nothing;

      if not (v_subject = any(v_valid_subjects)) then
        v_valid_subjects := array_append(v_valid_subjects, v_subject);
      end if;
    exception
      when foreign_key_violation then
        if not (v_subject = any(v_invalid_subjects)) then
          v_invalid_subjects := array_append(v_invalid_subjects, v_subject);
        end if;
    end;
  end loop;

  if v_delta >= 0 then
    update public.profile_levels
      set level = level + v_delta
    where user_id = v_uid
      and category = any(v_valid_subjects);
  else
    update public.profile_levels
      set level = greatest(level + v_delta, 0)
    where user_id = v_uid
      and category = any(v_valid_subjects);
  end if;

  insert into public.task_attempts(
    task_id, version_id, user_id, answer_data, evaluation, is_correct, xp_delta
  ) values (
    p_task_id, v_version_id, v_uid, coalesce(p_answer_data, '{}'::jsonb), v_eval, v_is_correct, v_delta
  );

  return v_eval || jsonb_build_object(
    'task_id', p_task_id,
    'version_id', v_version_id,
    'xp_delta', v_delta,
    'applied_subjects', to_jsonb(v_valid_subjects),
    'ignored_subjects', to_jsonb(v_invalid_subjects)
  );
end;
$$;

-- Backward-compatible wrapper used by existing Flutter method
create or replace function public.solve_task(
  p_task_id bigint,
  p_answer_data text
) returns boolean
language plpgsql
security definer
set search_path = public
as $$
declare
  v_eval jsonb;
begin
  v_eval := public.solve_task_v2(
    p_task_id,
    coalesce(nullif(trim(p_answer_data), ''), '{}')::jsonb,
    null
  );
  return coalesce((v_eval->>'is_correct')::boolean, false);
end;
$$;

-- -------------------------------------------------
-- 5) Optional helper: UI schema template (for editor guidance)
-- -------------------------------------------------

create or replace function public.get_task_ui_schema_v1()
returns jsonb
language sql
stable
as $$
  select jsonb_build_object(
    '$schema', 'https://json-schema.org/draft/2020-12/schema',
    'title', 'Task UI Schema v1',
    'type', 'object',
    'required', jsonb_build_array('version', 'screens'),
    'properties', jsonb_build_object(
      'version', jsonb_build_object('type', 'string', 'const', '1.0'),
      'theme', jsonb_build_object('type', 'object'),
      'screens', jsonb_build_object(
        'type', 'array',
        'items', jsonb_build_object(
          'type', 'object',
          'required', jsonb_build_array('id', 'elements'),
          'properties', jsonb_build_object(
            'id', jsonb_build_object('type', 'string'),
            'animation', jsonb_build_object('type', 'object'),
            'elements', jsonb_build_object(
              'type', 'array',
              'items', jsonb_build_object(
                'type', 'object',
                'required', jsonb_build_array('type', 'id'),
                'properties', jsonb_build_object(
                  'id', jsonb_build_object('type', 'string'),
                  'type', jsonb_build_object('type', 'string'),
                  'props', jsonb_build_object('type', 'object'),
                  'bind', jsonb_build_object('type', 'object')
                )
              )
            )
          )
        )
      )
    )
  );
$$;

-- -------------------------------------------------
-- 6) RLS
-- -------------------------------------------------

alter table public.tasks enable row level security;
alter table public.task_versions enable row level security;
alter table public.task_attempts enable row level security;

drop policy if exists tasks_select_policy on public.tasks;
create policy tasks_select_policy on public.tasks
for select to authenticated
using (
  visibility in ('public', 'unlisted')
  or created_by = auth.uid()
);

drop policy if exists tasks_insert_policy on public.tasks;
create policy tasks_insert_policy on public.tasks
for insert to authenticated
with check (created_by = auth.uid());

drop policy if exists tasks_update_policy on public.tasks;
create policy tasks_update_policy on public.tasks
for update to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

drop policy if exists tasks_delete_policy on public.tasks;
create policy tasks_delete_policy on public.tasks
for delete to authenticated
using (created_by = auth.uid());

drop policy if exists task_versions_select_policy on public.task_versions;
create policy task_versions_select_policy on public.task_versions
for select to authenticated
using (
  status = 'published'
  or created_by = auth.uid()
);

drop policy if exists task_versions_insert_policy on public.task_versions;
create policy task_versions_insert_policy on public.task_versions
for insert to authenticated
with check (created_by = auth.uid());

drop policy if exists task_versions_update_policy on public.task_versions;
create policy task_versions_update_policy on public.task_versions
for update to authenticated
using (created_by = auth.uid())
with check (created_by = auth.uid());

drop policy if exists task_versions_delete_policy on public.task_versions;
create policy task_versions_delete_policy on public.task_versions
for delete to authenticated
using (created_by = auth.uid());

drop policy if exists task_attempts_select_own on public.task_attempts;
create policy task_attempts_select_own on public.task_attempts
for select to authenticated
using (user_id = auth.uid());

drop policy if exists task_attempts_insert_own on public.task_attempts;
create policy task_attempts_insert_own on public.task_attempts
for insert to authenticated
with check (user_id = auth.uid());

-- function grants
revoke all on function public.solve_task_v2(bigint, jsonb, bigint) from public;
revoke all on function public.solve_task(bigint, text) from public;
revoke all on function public.evaluate_task_submission(bigint, bigint, jsonb) from public;

grant execute on function public.solve_task_v2(bigint, jsonb, bigint) to authenticated;
grant execute on function public.solve_task(bigint, text) to authenticated;
grant execute on function public.evaluate_task_submission(bigint, bigint, jsonb) to authenticated;
grant execute on function public.create_task_draft_version(bigint, text, jsonb, jsonb) to authenticated;
grant execute on function public.clone_task_version(bigint, bigint, text) to authenticated;
grant execute on function public.publish_task_version(bigint, bigint, boolean) to authenticated;
grant execute on function public.get_task_ui_schema_v1() to authenticated;

commit;

